#!/bin/sh
# postrm script for kali-gemini-hw
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
	    remove)
	        for file in etc/X11/xorg.conf \
                            etc/sddm.conf \
                            etc/adduser.conf \
			    etc/pulse/arm_droid_card_custom.pa \
			    etc/pulse/default.pa \
			    etc/skel/.config/kwinrc \
			    etc/skel/.gtkrc-2.0 \
			    etc/skel/.config/gtk-3.0/settings.ini \
			    etc/skel/.config/lxqt/lxqt-powermanagement.conf \
			    etc/skel/.config/lxqt/lxqt.conf \
			    etc/skel/.config/lxqt/session.conf; do
                            #<file 4>; do
                    rm -f $file		
                    if dpkg-divert --list | grep -F "${file}"; then
                        dpkg-divert --package kali-gemini-hw --remove --divert $file.original --rename $file
                    fi
		done
            ;;
    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 1
    ;;
esac

#DEBHELPER#

exit 0
